### ISSUE TITLE
VeniStaker review

### ISSUE THREAD

**Issue by o-p** [VeniceFinance/venice-farm#1]
Review file version 288f0a9cdcc6b8865f6ce9b6b6161f6acbf00f4b

### state mutation public functions

- [x] [stake](https://github.com/VeniceFinance/venice-farm/issues/1#issuecomment-1505017016)
- [x] [withdrawExpiredLocks](https://github.com/VeniceFinance/venice-farm/issues/1#issuecomment-1505032132)
- [x] [chefStake](https://github.com/VeniceFinance/venice-farm/issues/1#issuecomment-1505091663)
- [x] [chefWithdraw](https://github.com/VeniceFinance/venice-farm/issues/1#issuecomment-1505130145)
- [x] [chefWithdrawAll](https://github.com/VeniceFinance/venice-farm/issues/1#issuecomment-1505134903)
- [x] [claimReward](https://github.com/VeniceFinance/venice-farm/issues/1#issuecomment-1505139006)

### modifiers

- [x] [updateReward](https://github.com/VeniceFinance/venice-farm/issues/1#issuecomment-1506456252)

### owner functions

注意權限控管, 以及如果改動是否會讓系統計算出現問題

- [x] setMinters
    - 無法刪除 minter
- [x] setTreasuryAddr
- [x] setRatios
- [x] addReward
    - 看起來要避免加入 stakingToken
- [x] recoverERC20
- [x] approveRewardDistributor

### distributor functions

- [x] notifyRewardAmount

### others

- 目前不明意義的 chef 開頭 functions
    - 看起來是 chef 系列操作 userEarnings 相關; 非 chef 系列操作 locked & unlocked
- userLocks 理論上最多只會有 lockDuration / rewardsDuration = 13 筆, 但如果使用者一直 stake 卻不領出就可能會持續長大, 最終造成無法領出
    - 針對這種狀況, 是不是 stake 前先檢查下 userLocksEnd - userLocksStart < N 會比較好?
- 看起來 balances.unlocked 跟 balances.total 兩者擇一即可

**Comment by o-p** [comment]
### VeniStaker::`stake`

- [ ] [操作 token 前先記帳](https://github.com/VeniceFinance/venice-farm/blob/288f0a9cdcc6b8865f6ce9b6b6161f6acbf00f4b/contracts/VeniStaker.sol#L286-L288), 如果只有單一合約還好, 但如果有其他合約會依賴帳本判斷的話就可能出問題
- [ ] [unlockTime 這樣計算會變成往回退](https://github.com/VeniceFinance/venice-farm/blob/288f0a9cdcc6b8865f6ce9b6b6161f6acbf00f4b/contracts/VeniStaker.sol#L292), 例如 4/6 12:00 存入, 有可能被當成 4/1 00:00 存入, 是否符合設計? 目前寫法七天內存入的會鎖在同一筆紀錄

**Comment by o-p** [comment]
### VeniStaker::`withdrawExpiredLocks`

- [ ] 目前沒 `nonReentrant` 保護
- [ ] [userLockedEnd - 1 前面沒有先檢查是否 > 0](https://github.com/VeniceFinance/venice-farm/blob/288f0a9cdcc6b8865f6ce9b6b6161f6acbf00f4b/contracts/VeniStaker.sol#L312), 沒 lock assets 的使用者會有不好看的錯誤訊息
- [ ] 漏了 `updateReward` ?

**Comment by o-p** [comment]
### VeniStaker::`chefStake`

> 讓具有 VeniStaker::minter 身份的來源幫指定 address 寫入 userEarnings
> 並直接以 VeniStaker 合約 mint staking token

- 讓 Staker 自己 mint 有點怪, 不確定 tokenomic, 非 code 問題

**Comment by o-p** [comment]
### VeniStake::`chefWithdraw`

> 優先領出 unlocked assets
> 其次領出已到期的 userEarnings 部位
> 最後會去領出尚未到期的 userEarnings, 如果動用到此部位, 則會額外多扣 100%, 轉入 treasury & protocol

- [ ] [這邊](https://github.com/VeniceFinance/venice-farm/blob/288f0a9cdcc6b8865f6ce9b6b6161f6acbf00f4b/contracts/VeniStaker.sol#L382) 會將 remaining 部位 double
    - 建議把 mul(2) 部分寫成讀取 constant or property, 這邊寫 mul(2) 未來改規則容易漏而且閱讀不易
- [ ] ~**loop 掃完 userEarnings 後沒有檢查 remaining 還有沒有殘餘** (僅在一開始確認 earned > remaining), 因此假設用戶一開始 remaining 1000 / earned 1001 / realPenaltyAmount = 1000~
    - ~最終 user 領到預期的量 1000, userEarnings 被扣光, 僅損失 1~
    - ~protocol 會額外轉出 `realPenaltyAmount x treasuryRatio / totalRatio` 的 stakingToken 至 treasury, 可能 protocol 損失~

**Comment by o-p** [comment]
### VeniStake::`chefWithdrawAll`

**Comment by o-p** [comment]
### VeniStake::`claimReward`

**Comment by o-p** [comment]
### VeniStake::`updateReward`

**Comment by PassengerAndy** [comment]
1. stake & chefStake: 增加require   userEnd - userStart < 15
2.withdrawExpiredLocks:  增加 nonReentrant 保护， 先檢查 userLockedEnd - userLockedStart  > 0
3.會將 remaining 部位 double:   double 改为配置
